# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jochem/GitHub/Fontys/mo7-embedded-wrapper/mo7-embedded-wrapper/mo7-embedded-wrapper.srcs/sources_1/bd/design_1/ip/design_1_audio_codec_ctrl_0_0/design_1_audio_codec_ctrl_0_0.xci
# IP: The module: 'design_1_audio_codec_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Jochem/GitHub/Fontys/mo7-embedded-wrapper/mo7-embedded-wrapper/mo7-embedded-wrapper.gen/sources_1/bd/design_1/ip/design_1_audio_codec_ctrl_0_0/src/fifo/fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo || ORIG_REF_NAME==fifo} -quiet] -quiet

# XDC: c:/Users/Jochem/GitHub/Fontys/mo7-embedded-wrapper/mo7-embedded-wrapper/mo7-embedded-wrapper.gen/sources_1/bd/design_1/ip/design_1_audio_codec_ctrl_0_0/src/fifo/fifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo || ORIG_REF_NAME==fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: c:/Users/Jochem/GitHub/Fontys/mo7-embedded-wrapper/mo7-embedded-wrapper/mo7-embedded-wrapper.srcs/sources_1/bd/design_1/ip/design_1_audio_codec_ctrl_0_0/design_1_audio_codec_ctrl_0_0.xci
# IP: The module: 'design_1_audio_codec_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Jochem/GitHub/Fontys/mo7-embedded-wrapper/mo7-embedded-wrapper/mo7-embedded-wrapper.gen/sources_1/bd/design_1/ip/design_1_audio_codec_ctrl_0_0/src/fifo/fifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo || ORIG_REF_NAME==fifo} -quiet] -quiet

# XDC: c:/Users/Jochem/GitHub/Fontys/mo7-embedded-wrapper/mo7-embedded-wrapper/mo7-embedded-wrapper.gen/sources_1/bd/design_1/ip/design_1_audio_codec_ctrl_0_0/src/fifo/fifo.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo || ORIG_REF_NAME==fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
